version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9089:8000"
    volumes:
      - .:/app
    command: /venv/bin/python manage.py runserver 0.0.0.0:8000

